### PR TITLE
This fixes LMIO1; which contained files from lots of other places.

### PR DESCRIPTION
**Pull request by ams**

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
I suppose this is OK, but the commit messages doesn't always line up with the commits.

**Review by larsbrinkhoff — APPROVED** [review]

**Comment by ams** [comment]
Which message doesn't line up? I can amend it accordingly.

**Comment by larsbrinkhoff** [comment]
It's not terribly important, but "Duplicate files already living elsewhere." adds some files, where my expectation would be for it to only remove duplicate files.

And "lmio1/mouse.qfasl: Restore file" just removes a file.  How is that restoring?

Maybe quickly double check your commits do what you intended?

**Comment by ams** [comment]
> It's not terribly important, but "Duplicate files already living elsewhere." adds some files, where my expectation would be for it to only remove duplicate files.

Ah, I see; some SUDS in `LMDOC;`.  Fixed.

> And "lmio1/mouse.qfasl: Restore file" just removes a file. How is that restoring?

I don't see where it deletes the file; am I missing something?  It just modifies `LMIO1; MOUSE QFASL`, maybe git is reporting it as remvoed -- and then added?

**Comment by larsbrinkhoff** [comment]
I don't see the "mouse" commit any more.  But anyway, if you're happy about this, feel free to merge it.

**Comment by ams** [comment]
You comment faster than my network is capable of sending traffic.

**Pull request merged**
